language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

# container-based builds
sudo: false
addons:
  apt:
    packages:
    # packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    - libconfuse-dev
    - libncurses5-dev
    - libnl-3-dev
    - libnl-route-3-dev


install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update > /dev/null && brew install confuse ; fi

script:
  - ./.travis/run.sh
